monitor.alsa.rules = [
  {
    matches = [
      { device.name = "alsa_card.pci-0000_c4_00.5-platform-amd_sdw" }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c4_00.5-platform-amd_sdw.pro-output-2" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        node.description = "Internal Speakers (TAS2783)"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c4_00.5-platform-amd_sdw.pro-output-0" }
    ]
    actions = {
      update-props = {
        node.description = "Audio Jack (3.5mm)"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.pci-0000_c4_00.5-platform-amd_sdw.pro-input-1" }
    ]
    actions = {
      update-props = {
        node.description = "Audio Jack (3.5mm)"
      }
    }
  }
  {
    matches = [
      { node.name = "alsa_input.pci-0000_c4_00.5-platform-amd_sdw.pro-input-4" }
    ]
    actions = {
      update-props = {
        node.description = "Internal Microphone"
      }
    }
  }
  {
    matches = [
      { node.name = "~alsa_input.pci-0000_c4_00.5-platform-amd_sdw.pro-input-3" }
    ]
    actions = {
      update-props = {
        node.disabled = true
        node.description = "SmartAmp IV Sense (unused)"
      }
    }
  }
]
