monitor.alsa.rules = [
  {
    matches = [
      { device.name = "~alsa_card.pci-*-platform-amd_sdw" }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = true
        device.profile = "HiFi (Mic, Speaker)"
      }
    }
  }
  {
    matches = [
      { node.name = "~alsa_output.pci-*-platform-amd_sdw.HiFi__Speaker__sink" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
